# Generated by Django 5.2.14 on 2026-06-16 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('job_types', models.JSONField(blank=True, default=list)),
                ('experience_levels', models.JSONField(blank=True, default=list)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('radius_km', models.IntegerField(default=50)),
                ('frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='instant', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'job_alerts',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField()),
                ('required_keywords', models.JSONField(blank=True, default=list)),
                ('nice_to_have_keywords', models.JSONField(blank=True, default=list)),
                ('employment_type', models.CharField(choices=[('white_collar', 'White collar'), ('casual', 'Casual')], default='white_collar', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('on_hold', 'On hold')], default='open', max_length=20)),
                ('auto_reject_threshold', models.IntegerField(default=0)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'job_postings',
            },
        ),
        migrations.CreateModel(
            name='JobAlertLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(db_column='alert_id', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='recruitment.jobalert')),
                ('job_posting', models.ForeignKey(db_column='job_posting_id', on_delete=django.db.models.deletion.CASCADE, to='recruitment.jobposting')),
            ],
            options={
                'db_table': 'job_alert_logs',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('cv_url', models.CharField(blank=True, default='', max_length=500)),
                ('cv_text', models.TextField(blank=True, null=True)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('ai_extracted_skills', models.JSONField(blank=True, default=list)),
                ('ai_experience_years', models.FloatField(blank=True, null=True)),
                ('ai_education', models.CharField(blank=True, max_length=200, null=True)),
                ('current_stage', models.CharField(choices=[('screened', 'Screened'), ('interview_l1', 'Interview L1'), ('interview_l2', 'Interview L2'), ('offer_sent', 'Offer sent'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='screened', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_consent', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('data_retention_months', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(default='careers_site', max_length=50)),
                ('job_posting', models.ForeignKey(db_column='job_posting_id', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.jobposting')),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
    ]
