# Generated by Django 5.2.14 on 2026-06-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('company_id', None)), fields=('slug',), name='unique_global_role_slug'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('company_id', None), _negated=True), fields=('company_id', 'slug'), name='unique_company_role_slug'),
        ),
    ]
