# Generated by Django 5.2.14 on 2026-06-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_announcement_leaverequest_leavebalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'ordering': ['-year', 'leave_type']},
        ),
    ]
