# Generated by Django 5.2.14 on 2026-06-16 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_leavebalance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('template_id', models.UUIDField(blank=True, null=True)),
                ('period_quarter', models.IntegerField()),
                ('period_year', models.IntegerField()),
                ('targets', models.JSONField(blank=True, default=list)),
                ('scores', models.JSONField(blank=True, default=list)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kpi_assignments',
                'ordering': ['-period_year', '-period_quarter'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('record_type', models.CharField(max_length=100)),
                ('file_url', models.TextField(blank=True, default='')),
                ('fitness_status', models.CharField(choices=[('fit', 'Fit'), ('fit_with_conditions', 'Fit with conditions'), ('unfit', 'Unfit')], default='fit', max_length=20)),
                ('issued_by', models.CharField(blank=True, max_length=200, null=True)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('reviewer_id', models.UUIDField(blank=True, null=True)),
                ('period', models.CharField(max_length=50)),
                ('rating', models.PositiveSmallIntegerField()),
                ('strengths', models.TextField(blank=True, null=True)),
                ('improvements', models.TextField(blank=True, null=True)),
                ('promotion_recommended', models.BooleanField(default=False)),
                ('award_given', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'performance_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('trainer_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_mandatory', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'training_sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('candidate_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('check_type', models.CharField(choices=[('criminal', 'Criminal'), ('credit', 'Credit'), ('employment', 'Employment'), ('education', 'Education'), ('professional', 'Professional')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('passed', 'Passed'), ('failed', 'Failed'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('requested_by', models.UUIDField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('document_url', models.TextField(blank=True, null=True)),
                ('document_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=200, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('clearance_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'background_checks',
                'ordering': ['-requested_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('employee_id__isnull', False), ('candidate_id__isnull', False), _connector='OR'), name='background_check_has_subject')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOnboardingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('doc_type', models.CharField(choices=[('contract', 'Contract'), ('id', 'ID'), ('nssf', 'NSSF'), ('nhif', 'NHIF'), ('kra_pin', 'KRA PIN'), ('bank_details', 'Bank details')], max_length=20)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('uploaded', 'Uploaded'), ('verified', 'Verified')], default='missing', max_length=20)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_onboarding_documents',
                'unique_together': {('employee_id', 'doc_type')},
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('attendance_status', models.CharField(choices=[('enrolled', 'Enrolled'), ('attended', 'Attended'), ('completed', 'Completed'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], default='enrolled', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('certificate_url', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='hr.trainingsession')),
            ],
            options={
                'db_table': 'training_enrollments',
                'unique_together': {('session', 'employee_id')},
            },
        ),
    ]
