# Generated by Django 5.2.14 on 2026-06-12 13:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('center_lat', models.FloatField()),
                ('center_lng', models.FloatField()),
                ('radius_m', models.PositiveIntegerField(default=200)),
                ('work_start', models.TimeField(default='08:00')),
                ('work_end', models.TimeField(default='17:00')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'work_zones',
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(db_index=True)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(choices=[('check_in', 'Check in'), ('check_out', 'Check out'), ('location_ping', 'Location ping'), ('geofence_exit', 'Geofence exit'), ('geofence_enter', 'Geofence enter')], max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('zone_id', models.UUIDField(blank=True, null=True)),
                ('in_zone', models.BooleanField(null=True)),
                ('face_verified', models.BooleanField(null=True)),
                ('face_confidence', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=255)),
                ('out_of_zone_reason', models.TextField(blank=True, default='')),
                ('source_app', models.CharField(default='pwa', max_length=20)),
            ],
            options={
                'db_table': 'attendance_events',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['company_id', 'time'], name='attendance__company_4aa7cc_idx'), models.Index(fields=['employee_id', 'time'], name='attendance__employe_502965_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeofenceViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(db_index=True)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reason_submitted', 'Reason submitted'), ('reviewed', 'Reviewed')], default='open', max_length=20)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workzone')),
            ],
            options={
                'db_table': 'geofence_violations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeZoneAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('company_id', models.UUIDField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.workzone')),
            ],
            options={
                'db_table': 'employee_zone_assignments',
                'unique_together': {('employee_id', 'zone')},
            },
        ),
    ]
