# Generated by Django 5.2.14 on 2026-05-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pesapal_sandbox',
            field=models.BooleanField(default=True, help_text='Use PesaPal sandbox environment'),
        ),
    ]
