# Generated by Django 5.2.14 on 2026-06-12 13:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_company_pesapal_sandbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField()),
                ('employee_number', models.CharField(max_length=50)),
                ('department', models.TextField(blank=True, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern')], max_length=20)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('resigned', 'Resigned')], default='active', max_length=20)),
                ('manager_id', models.UUIDField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_duration_months', models.IntegerField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money')], max_length=10)),
                ('bank_name', models.TextField(blank=True, null=True)),
                ('bank_account', models.TextField(blank=True, null=True)),
                ('mpesa_number', models.TextField(blank=True, null=True)),
                ('airtel_number', models.TextField(blank=True, null=True)),
                ('nssf_number', models.TextField(blank=True, null=True)),
                ('nhif_number', models.TextField(blank=True, null=True)),
                ('kra_pin', models.TextField(blank=True, null=True)),
                ('id_number', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('nationality', models.TextField(blank=True, null=True)),
                ('next_of_kin_name', models.TextField(blank=True, null=True)),
                ('next_of_kin_phone', models.TextField(blank=True, null=True)),
                ('next_of_kin_relationship', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApproverConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(db_index=True, unique=True)),
                ('required_approvals', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payroll_approver_configs',
            },
        ),
        migrations.CreateModel(
            name='PayrollDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('payroll_run_id', models.UUIDField(db_index=True)),
                ('payroll_record_id', models.UUIDField(blank=True, null=True)),
                ('doc_type', models.CharField(choices=[('payroll_pdf', 'Payroll PDF'), ('payroll_excel', 'Payroll Excel'), ('payslip_pdf', 'Payslip PDF'), ('signed_pdf', 'Signed PDF')], max_length=20)),
                ('file', models.FileField(upload_to='payroll_documents/%Y/%m/')),
                ('sha256', models.CharField(max_length=64)),
                ('password_protected', models.BooleanField(default=False)),
                ('docuseal_template_id', models.CharField(blank=True, default='', max_length=100)),
                ('docuseal_submission_id', models.CharField(blank=True, default='', max_length=100)),
                ('is_signed', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('generated_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payroll_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'managed': False, 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='paymentbatch',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='payrollrecord',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='payrollrun',
            options={'managed': False, 'ordering': ['-period_year', '-period_month']},
        ),
        migrations.CreateModel(
            name='PayrollApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('payroll_run_id', models.UUIDField(db_index=True)),
                ('approver_user_id', models.UUIDField()),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('via', models.CharField(choices=[('dashboard', 'Dashboard'), ('one_tap', 'One-tap link'), ('docuseal', 'DocuSeal signature')], default='dashboard', max_length=10)),
                ('comment', models.TextField(blank=True, default='')),
                ('docuseal_submitter_slug', models.CharField(blank=True, default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'payroll_approvals',
                'ordering': ['-signed_at'],
                'unique_together': {('payroll_run_id', 'approver_user_id')},
            },
        ),
        migrations.CreateModel(
            name='PayrollApprover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.UUIDField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='payroll.approverconfig')),
            ],
            options={
                'db_table': 'payroll_approvers',
                'ordering': ['order'],
                'unique_together': {('config', 'user_id')},
            },
        ),
        # Employee was renamed to EmployeeProfile (managed=False Supabase mirror);
        # state-only — the table was never owned by Django.
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name='Employee')],
            database_operations=[],
        ),
    ]
