# Generated by Django 5.2.14 on 2026-06-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employeeprofile_worker_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollapproval',
            name='signature_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
